// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetXDeviceInfo(arg1) {
  return window['go']['main']['App']['GetXDeviceInfo'](arg1);
}

export function ListDisplays() {
  return window['go']['main']['App']['ListDisplays']();
}

export function ListXDevices() {
  return window['go']['main']['App']['ListXDevices']();
}
