// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetXDeviceInfo(arg1:string):Promise<string>;

export function ListDisplays():Promise<Array<number>>;

export function ListXDevices():Promise<Array<string>>;
